    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    http2 on; 
    add_header Alt-Svc 'h2=":443"';

    #Temporary disable http3 since nginx  default docker build does not support it
    #listen 443 quic;
    #listen [::]:443 quic;
    #common-header.conf instead of include /etc/nginx/common.d/common-h3.conf;
    include /etc/nginx/common.d/common-header.conf;