    http3 on; 
    quic_retry on;

    include /etc/nginx/common.d/common-header.conf;

    #QUIC HEADER
    add_header Alt-Svc 'h3=":443", h2=":443"';
    add_header QUIC-Status $http3;
    add_header X-Quic 'h3';