services:
  unbound:
    build: ./unbound-docker/
    container_name: unbound
    ports:
      - "5335:5335/udp"
      - "5335:5335/tcp"
    privileged: true
    networks:
      - dns_network
    dns:
      - 1.1.1.2
      - 1.0.0.2
      - 2606:4700:4700::1112
      - 2606:4700:4700::1002
    restart: unless-stopped

  pihole:
    container_name: pihole
    depends_on:
      - unbound
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "123:123/udp"
      - "44353:443/tcp"
    environment:
      TZ: 'Europe/Lisbon'
      FTLCONF_dns_upstreams: 'unbound#5335'
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_dns_piholePTR: 'HOSTNAMEFQDN'
      FTLCONF_dns_replyWhenBusy: 'BLOCK'
      FTLCONF_dns_domainNeeded: true
      FTLCONF_dns_expandHosts: true
      FTLCONF_dns_dnssec: true
      FTLCONF_dns_blocking_active: true
      FTLCONF_dns_rateLimit_count: 1200
      FTLCONF_ntp_sync_rtc_set: true
      FTLCONF_webserver_port: +443s
      FTLCONF_webserver_session_timeout: 2592000
    volumes:
      - '/etc/pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
      - SYS_NICE
      - SYS_TIME
    networks:
      - dns_network
    dns:
      - 1.1.1.2
      - 1.0.0.2
      - 2606:4700:4700::1112
      - 2606:4700:4700::1002
    healthcheck:
      test: ["CMD", "dig", "+ad", "+short", "dnssec.works", "@127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  doh:
    build: ./doh-docker/
    container_name: doh
    depends_on:
      - pihole
    ports:
      - "3000:3000/tcp"
    environment:
      - DOH_HOSTNAME=${DOH_HOSTNAME}
      - DOH_UPSTREAM_DNS=${DOH_UPSTREAM_DNS:-pihole:53}
      - DOH_PATH_PREFIX=${DOH_PATH_PREFIX:-query-dns}
      - DOH_PUBLIC_PORT=${DOH_PUBLIC_PORT:-443}
    networks:
      - dns_network
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  dns_network:
    driver: bridge
    enable_ipv6: true