server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    include /etc/nginx/common.d/common-header.conf;

    access_log off;
    log_not_found off;

    location /.well-known/acme-challenge/ {
        allow all;
        root /var/www/certbot;
    }

    return 308 https://$host$request_uri;
}

