upstream dns {
    zone dns 64k;
    server 172.28.0.3:53;
}

server {
    listen 853 ssl;
    listen [::]:853 ssl;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    
    ssl_session_cache shared:StreamSSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets on;

    proxy_pass dns;
}